import express from 'express';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import helmet from 'helmet';
import morgan from 'morgan';
import {config} from './config.js';
import {initJobs} from './services/jobs.js';
import api from './routes/api.js';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
await initJobs();
const app=express();app.disable('x-powered-by');app.use(helmet({crossOriginResourcePolicy:false}));app.use(express.json({limit:'1mb'}));app.use(morgan('combined'));app.use('/api',api);app.use(express.static(path.resolve(__dirname,'../../public')));app.use((req,res)=>res.sendFile(path.resolve(__dirname,'../../public/index.html')));
app.listen(config.port,()=>console.log(`SX CONVERTER listening on :${config.port}`));
